***Python library - pandas & numpy***

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
ar = np.array([2,7,9,4,10])

In [ ]:
print(ar)

[ 2  7  9  4 10]

In [ ]:
print(ar.sum())
print(ar.min())
print(ar.max())
print(ar.mean())
print(ar.std())

32
2
10
6.4
3.006659275674582

***operations - in copy ; doesn't modify original array***

In [ ]:
print(ar + 5)
print(ar - 5)
print(ar * 5)
print(ar / 5)

[ 7 12 14  9 15]
[-3  2  4 -1  5]
[10 35 45 20 50]
[0.4 1.4 1.8 0.8 2. ]

In [ ]:
print(np.pow(ar,2))
print(np.sqrt(ar))

[  4  49  81  16 100]
[1.41421356 2.64575131 3.         2.         3.16227766]

***slicing***

*  ***print(ar[ start : end+1 )***

In [ ]:
print(ar)
print(ar[2:4])
print(ar[2:4])

[ 2  7  9  4 10]
[9 4]
[9 4]


*   ***import dataset using Pandas data frame***
*   ***CSV -  comma separated values***

In [ ]:
path = "/content/drive/MyDrive/Colab Notebooks/ML/Pandas & numpy/Data.csv"

In [ ]:
df = pd.read_csv(path)

In [ ]:
df

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

df["col name"]

In [ ]:
df["Age"]

0    44.0
1    27.0
2    30.0
3    38.0
4    40.0
5    35.0
6     NaN
7    48.0
8    50.0
9    37.0
Name: Age, dtype: float64

2D - to show multiple col

In [ ]:
df[["Age", "Salary", "Country"]]

    Age   Salary  Country
0  44.0  72000.0   France
1  27.0  48000.0    Spain
2  30.0  54000.0  Germany
3  38.0  61000.0    Spain
4  40.0      NaN  Germany
5  35.0  58000.0   France
6   NaN  52000.0    Spain
7  48.0  79000.0   France
8  50.0  83000.0  Germany
9  37.0  67000.0   France

***head() - print first 5 rows bt deafult***

In [ ]:
df.head()

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

***df.head(no of rows)***

In [ ]:
df.head(9)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No

***shape - gives row & column***

In [ ]:
df.shape

(10, 4)

***df.describe() - apply on numerical values,used to generate descriptive statistics ***

In [ ]:
df.describe()

             Age        Salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

***df.info() - gives summary***

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    10 non-null     object
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object
dtypes: float64(2), object(2)
memory usage: 452.0+ bytes

***df.isna() -  is a method used to detect missing or null values in a DataFrame***


*   isna - is not available

In [ ]:
df.isna()

   Country    Age  Salary  Purchased
0    False  False   False      False
1    False  False   False      False
2    False  False   False      False
3    False  False   False      False
4    False  False    True      False
5    False  False   False      False
6    False   True   False      False
7    False  False   False      False
8    False  False   False      False
9    False  False   False      False

In [ ]:
df.isna().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

***df[df.isna().any(axis=1)] - used to filter and return all rows in a Pandas DataFrame that contain at least one missing or NaN value***

In [ ]:
df[df.isna().any(axis=1)]

   Country   Age   Salary Purchased
4  Germany  40.0      NaN       Yes
6    Spain   NaN  52000.0        No

***drop age col***

In [62]:
df = df.drop(columns=["Age"])

In [63]:
df.head()

   Country   Salary Purchased
0   France  72000.0        No
1    Spain  48000.0       Yes
2  Germany  54000.0        No
3    Spain  61000.0        No
4  Germany      NaN       Yes